### ISSUE TITLE
how to use with localhost?

### ISSUE THREAD

**Issue by mauricionr** [Azure/azure-documentdb-js#6]

**Comment by ryancrawcour** [comment]
Not sure I understand the question. Are you trying to run a web application locally connecting to DocumentDB in Azure?

**Comment by mauricionr** [comment]
I'm running Iisexpress and i'm trying to make a crud with documentdb.
When i try to query the database my Authorization Header is always undefined.

**Comment by mauricionr** [comment]
here is my repo....
https://github.com/mauricionr/site5

**Comment by ryancrawcour** [comment]
I think the problem is in the following;

161 				auth.resourceTokens = {}; 
162 				auth.resourceTokens.collectionId = v.collectionId; 
163 				auth.resourceTokens.databaseId = v.databaseId; 
164                          auth.masterKey = v.authKey;

auth.resourceTokens["/dbs/db _rid/colls/coll _rid"] = some auth token you got back from a permission server

here "/dbs/db _rid/colls/coll _rid" - maps to a Collection.selfLink
the value should be the resource token you would need to generate using the master key. 

var resourceTokens = { resouceLink1: permissionToken1, resourceLink2: permissionToken2};
var client = DocumentDB.createClient(documentdbService, {resourceTokens: resourceToken});

it appears that you are building a web application with Angular and as such even if you got past this the next thing you would run in to is a cross-domain scripting issue. 
it will work locally, but deployed to a website it will fail cross-domain exceptions.

if you are building a web application connecting to DocumentDB we would recommend you build the middletier with node.js and have your client javascript call this.

**Comment by mauricionr** [comment]
Tks in advance!
